dataset_config:
  sampling_prob: [0.7, 0.3]
  dataset_name: piast_joint
  data_dir: ./data/datasets/piast_joint  
  debug_input: false

  yt_data_dir: ./data/datasets/piast_yt  
  at_data_dir: ./data/datasets/piast_at

  text:
    max_seq_length: 77 
    tokenizer: robertatokenizer 
    text_type: caption

  audio:
    dir: ./data/datasets/piast_yt/audio
    sr: 16000
    crop_length: 20 
    random_crop: true
    augment: false
    p_noise: 0.3
    p_pitch_shift: 0.4
  midi:
    dir: ./data/datasets/piast_yt
    tgt_len: 512
    n_vocab_type: 4
