dataset_config:
  dataset_name: piast_yt
  data_dir: ./data/datasets/piast_yt
  debug_input: false

  text:
    max_seq_length: 77 
    tokenizer: robertatokenizer 
  audio:
    dir: ./data/datasets/piast_yt/audio
    sr: 16000
    crop_length: 20 
    random_crop: true
    augment: false
    p_noise: 0.3
    p_pitch_shift: 0.4
  midi:
    dir: ./data/datasets/piast_yt
    tgt_len: 512
    n_vocab_type: 4